export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENT = "GET_COMMENT"
export const ADD_COMMENT = "ADD_COMMENT"
export const EDIT_COMMENT = "EDIT_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"

